version: '2.0'
services:
  transmission:
    container_name: transmission
    image: jaymoulin/rpi-transmission
    restart: always
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - USERNAME=admin
      - PASSWORD=admin
    volumes:
      - /home/pi/transmission/torrents:/to_download
      - /home/pi/transmission/downloaded:/output
